services:
  raffleking:
    image: raffleking
    build:
      context: .
      dockerfile: RaffleKing/Dockerfile
    ports:
      - 8001:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on: 
      - db
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=CM4025secure123!
    ports:
      - 8002:1433
    volumes:
      - sql_data:/var/opt/mssql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    
volumes: 
  sql_data:
